spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

    # 仅支持 http/https，不限定响应内容格式
    remote:
#      - name: 'example rule' #规则名称
#        path: 'https://example.org/rule.txt' #规则地址
#      - 'https://example.org/rule2.txt' #旧版写法, 不推荐
     
      - name: 'Adguard Annyoyances optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt'
      - name: 'Adguard Chinese filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_224_Chinese/filter.txt'
      - name: 'Adguard DNS filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_15_DnsFilter/filter.txt'
      - name: 'Adguard Experimental filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_5_Experimental/filter.txt'
      - name: 'Adguard Mobile Ads filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_11_Mobile/filter.txt'
      - name: 'Adguard Social Media filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_4_Social/filter.txt'
      - name: 'Adguard Social Media filter optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/4_optimized.txt'
      - name: 'Adguard Tracking Protection filter'
        path: 'https://filters.adtidy.org/extension/ublock/filters/3.txt'
      - name: 'Adguard URL Tracking Parameters filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_17_TrackParam/filter.txt'
      - name: 'AdRules AdBlock List Plus Cats-Team'
        path: 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/adblock_plus.txt'
      - name: 'anti-AD for AdGuard'
        path: 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt'
      - name: 'AWAvenue 秋风广告规则 (AWAvenue-Ads-Rule)'
        path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'
      - name: 'Block Third-Party Fonts'
        path: 'https://github.com/yokoffing/filterlists/raw/main/block_third_party_fonts.txt'
      - name: 'Browse Websites Without Logging In'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/BrowseWebsitesWithoutLoggingIn.txt'
      - name: 'bypass-paywalls-clean-filters'
        path: 'https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt'
      - name: 'Dandelion Sprouts Annoyances List'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/AnnoyancesList'
      - name: 'Dandelion Sprouts Browse Websites Without Logging In'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/BrowseWebsitesWithoutLoggingIn.txt'
      - name: 'DD-AD'
        path: 'https://github.com/afwfv/DD-AD/raw/main/rule/DD-AD.txt'
      - name: 'EasyList + AdGuard Base filter Optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/2_optimized.txt'
      - name: 'EasyList Chat Widgets'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-chat.txt'
      - name: 'EasyList Cookie List'
        path: 'https://ublockorigin.pages.dev/thirdparties/easylist-cookies.txt'
      - name: 'EasyList Newsletter List'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-newsletters.txt'
      - name: 'EasyList Notifications List'
        path: 'https://ublockorigin.pages.dev/thirdparties/easylist-notifications.txt'
      - name: 'EasyList Other Annoyances List'
        path: 'https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-annoyances.txt'
      - name: 'EasyList Social List'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-social.txt'
      - name: 'Fanboy Annoyances optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt'
      - name: 'HaGeZis Ultimate DNS Blocklist'
        path: 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt'
      - name: 'I Dont Care About Cookies'
        path: 'https://www.i-dont-care-about-cookies.eu/abp/'
      - name: 'Legitimate URL Shortener List'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/LegitimateURLShortener.txt'
      - name: 'Oisd Big'
        path: 'https://big.oisd.nl/'
      - name: 'o0HalfLife0o ad block list'
        path: 'https://github.com/o0HalfLife0o/list/raw/master/ad-pc.txt'
      - name: 'Peter Lowes Ad and tracking server list'
        path: 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus'
      - name: 'Social Media & Share Filter List'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/SocialShareList.txt'
      - name: 'Twitch: Pure Viewing Experience'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/TwitchPureViewing'
      - name: 'uBlock Filters - AD'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.min.txt'
      - name: 'uBlock Filters - Annoyances'
        path: 'https://ublockorigin.pages.dev/filters/annoyances.min.txt'
      - name: 'uBlock Filters - Annoyances optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt'
      - name: 'uBlock Filters - Cookie Notices'
        path: 'https://ublockorigin.github.io/uAssetsCDN/filters/annoyances-cookies.txt'
      - name: 'uBlock Filters - Privacy'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/privacy.min.txt'
      - name: 'uBlock Filters - Quick Fixes'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/quick-fixes.min.txt'
      - name: 'uBlock Filters - Unbreak'
        path: 'https://ublockorigin.pages.dev/filters/unbreak.min.txt'
      - name: 'YouTube Clear View'
        path: 'https://github.com/yokoffing/filterlists/raw/main/youtube_clear_view.txt'
      - name: 'yokoffing annoyance list'
        path: 'https://github.com/yokoffing/filterlists/raw/main/annoyance_list.txt'
      - name: 'yokoffing block third party fonts'
        path: 'https://github.com/yokoffing/filterlists/raw/main/block_third_party_fonts.txt'
      - name: '1Host Pro'
        path: 'https://o0.pages.dev/Pro/adblock.txt'
      - name: '大圣净化'
        path: 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts'
      - name: 'NoAppDownload'
        path: 'https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt'

    #本地规则请将文件放置到项目路径rule目录中
    local:
#      - name: 'local rule'
#        path: 'local-rule.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/fordes123/ad-filters-subscriber/
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
